apiVersion: "v1"
kind: ConfigMap
metadata:
  name: config-map-postgre-sql
data:
  DB_NAME: mydatabase_toan
  DB_USERNAME: myuser_toan
  DB_HOST: postgresql-service
  DB_PORT: "5432"
---
apiVersion: "v1"
kind: Secret
metadata:
  name: secret-db-password
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZF90b2Fu